package model;
// Generated Oct 30, 2016 9:18:27 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Choose generated by hbm2java
 */
public class Choose  implements java.io.Serializable {


     private Integer id;
     private String sesId;
     private Integer proId;
     private String proName;
     private String proUrl;
     private Double price;
     private Integer quantity;
     private Double total;
     private Date chTime;
     private String proSize;

    public Choose() {
    }

	
    public Choose(String sesId, Date chTime) {
        this.sesId = sesId;
        this.chTime = chTime;
    }
    public Choose(String sesId, Integer proId, String proName, String proUrl, Double price, Integer quantity, Double total, Date chTime, String proSize) {
       this.sesId = sesId;
       this.proId = proId;
       this.proName = proName;
       this.proUrl = proUrl;
       this.price = price;
       this.quantity = quantity;
       this.total = total;
       this.chTime = chTime;
       this.proSize = proSize;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getSesId() {
        return this.sesId;
    }
    
    public void setSesId(String sesId) {
        this.sesId = sesId;
    }
    public Integer getProId() {
        return this.proId;
    }
    
    public void setProId(Integer proId) {
        this.proId = proId;
    }
    public String getProName() {
        return this.proName;
    }
    
    public void setProName(String proName) {
        this.proName = proName;
    }
    public String getProUrl() {
        return this.proUrl;
    }
    
    public void setProUrl(String proUrl) {
        this.proUrl = proUrl;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Date getChTime() {
        return this.chTime;
    }
    
    public void setChTime(Date chTime) {
        this.chTime = chTime;
    }
    public String getProSize() {
        return this.proSize;
    }
    
    public void setProSize(String proSize) {
        this.proSize = proSize;
    }




}


