package model;
// Generated Oct 30, 2016 9:18:27 AM by Hibernate Tools 4.3.1



/**
 * DelivaryCost generated by hbm2java
 */
public class DelivaryCost  implements java.io.Serializable {


     private int delivaryId;
     private String zoneName;
     private Double delivaryCost;

    public DelivaryCost() {
    }

	
    public DelivaryCost(int delivaryId) {
        this.delivaryId = delivaryId;
    }
    public DelivaryCost(int delivaryId, String zoneName, Double delivaryCost) {
       this.delivaryId = delivaryId;
       this.zoneName = zoneName;
       this.delivaryCost = delivaryCost;
    }
   
    public int getDelivaryId() {
        return this.delivaryId;
    }
    
    public void setDelivaryId(int delivaryId) {
        this.delivaryId = delivaryId;
    }
    public String getZoneName() {
        return this.zoneName;
    }
    
    public void setZoneName(String zoneName) {
        this.zoneName = zoneName;
    }
    public Double getDelivaryCost() {
        return this.delivaryCost;
    }
    
    public void setDelivaryCost(Double delivaryCost) {
        this.delivaryCost = delivaryCost;
    }




}


