package model;
// Generated Oct 30, 2016 9:18:27 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DelivaryAddress generated by hbm2java
 */
public class DelivaryAddress  implements java.io.Serializable {


     private Integer delivaryId;
     private String shoperName;
     private String email;
     private String phone;
     private String district;
     private String country;
     private String zipCode;
     private String reciveTime;
     private Date orderTime;
     private String address;
     private String comments;

    public DelivaryAddress() {
    }

    public DelivaryAddress(String shoperName, String email, String phone, String district, String country, String zipCode, String reciveTime, Date orderTime, String address, String comments) {
       this.shoperName = shoperName;
       this.email = email;
       this.phone = phone;
       this.district = district;
       this.country = country;
       this.zipCode = zipCode;
       this.reciveTime = reciveTime;
       this.orderTime = orderTime;
       this.address = address;
       this.comments = comments;
    }
   
    public Integer getDelivaryId() {
        return this.delivaryId;
    }
    
    public void setDelivaryId(Integer delivaryId) {
        this.delivaryId = delivaryId;
    }
    public String getShoperName() {
        return this.shoperName;
    }
    
    public void setShoperName(String shoperName) {
        this.shoperName = shoperName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getZipCode() {
        return this.zipCode;
    }
    
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }
    public String getReciveTime() {
        return this.reciveTime;
    }
    
    public void setReciveTime(String reciveTime) {
        this.reciveTime = reciveTime;
    }
    public Date getOrderTime() {
        return this.orderTime;
    }
    
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }




}


