package model;
// Generated Oct 30, 2016 9:18:27 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ProOrder generated by hbm2java
 */
public class ProOrder  implements java.io.Serializable {


     private Integer orderId;
     private Integer proId;
     private Integer userId;
     private Date orderDate;
     private Integer orderQty;
     private Double totalPrice;
     private String orderStatus;
     private Integer delivaryId;

    public ProOrder() {
    }

    public ProOrder(Integer proId, Integer userId, Date orderDate, Integer orderQty, Double totalPrice, String orderStatus, Integer delivaryId) {
       this.proId = proId;
       this.userId = userId;
       this.orderDate = orderDate;
       this.orderQty = orderQty;
       this.totalPrice = totalPrice;
       this.orderStatus = orderStatus;
       this.delivaryId = delivaryId;
    }
   
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
    public Integer getProId() {
        return this.proId;
    }
    
    public void setProId(Integer proId) {
        this.proId = proId;
    }
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }
    public Integer getOrderQty() {
        return this.orderQty;
    }
    
    public void setOrderQty(Integer orderQty) {
        this.orderQty = orderQty;
    }
    public Double getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
    }
    public String getOrderStatus() {
        return this.orderStatus;
    }
    
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }
    public Integer getDelivaryId() {
        return this.delivaryId;
    }
    
    public void setDelivaryId(Integer delivaryId) {
        this.delivaryId = delivaryId;
    }




}


