package model;
// Generated Oct 30, 2016 9:18:27 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Purchase generated by hbm2java
 */
public class Purchase  implements java.io.Serializable {


     private Integer id;
     private Integer proId;
     private String proName;
     private String proSize;
     private Double proPrice;
     private Integer proQty;
     private Double total;
     private Date purDate;

    public Purchase() {
    }

    public Purchase(Integer proId, String proName, String proSize, Double proPrice, Integer proQty, Double total, Date purDate) {
       this.proId = proId;
       this.proName = proName;
       this.proSize = proSize;
       this.proPrice = proPrice;
       this.proQty = proQty;
       this.total = total;
       this.purDate = purDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getProId() {
        return this.proId;
    }
    
    public void setProId(Integer proId) {
        this.proId = proId;
    }
    public String getProName() {
        return this.proName;
    }
    
    public void setProName(String proName) {
        this.proName = proName;
    }
    public String getProSize() {
        return this.proSize;
    }
    
    public void setProSize(String proSize) {
        this.proSize = proSize;
    }
    public Double getProPrice() {
        return this.proPrice;
    }
    
    public void setProPrice(Double proPrice) {
        this.proPrice = proPrice;
    }
    public Integer getProQty() {
        return this.proQty;
    }
    
    public void setProQty(Integer proQty) {
        this.proQty = proQty;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Date getPurDate() {
        return this.purDate;
    }
    
    public void setPurDate(Date purDate) {
        this.purDate = purDate;
    }




}


