package model;
// Generated Oct 30, 2016 9:18:27 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Sell generated by hbm2java
 */
public class Sell  implements java.io.Serializable {


     private Integer purId;
     private Integer proId;
     private String proName;
     private Double purPrice;
     private Double sellPrice;
     private Integer sellQty;
     private Double sellTotal;
     private Double profit;
     private Date sellDate;

    public Sell() {
    }

	
    public Sell(Date sellDate) {
        this.sellDate = sellDate;
    }
    public Sell(Integer proId, String proName, Double purPrice, Double sellPrice, Integer sellQty, Double sellTotal, Double profit, Date sellDate) {
       this.proId = proId;
       this.proName = proName;
       this.purPrice = purPrice;
       this.sellPrice = sellPrice;
       this.sellQty = sellQty;
       this.sellTotal = sellTotal;
       this.profit = profit;
       this.sellDate = sellDate;
    }
   
    public Integer getPurId() {
        return this.purId;
    }
    
    public void setPurId(Integer purId) {
        this.purId = purId;
    }
    public Integer getProId() {
        return this.proId;
    }
    
    public void setProId(Integer proId) {
        this.proId = proId;
    }
    public String getProName() {
        return this.proName;
    }
    
    public void setProName(String proName) {
        this.proName = proName;
    }
    public Double getPurPrice() {
        return this.purPrice;
    }
    
    public void setPurPrice(Double purPrice) {
        this.purPrice = purPrice;
    }
    public Double getSellPrice() {
        return this.sellPrice;
    }
    
    public void setSellPrice(Double sellPrice) {
        this.sellPrice = sellPrice;
    }
    public Integer getSellQty() {
        return this.sellQty;
    }
    
    public void setSellQty(Integer sellQty) {
        this.sellQty = sellQty;
    }
    public Double getSellTotal() {
        return this.sellTotal;
    }
    
    public void setSellTotal(Double sellTotal) {
        this.sellTotal = sellTotal;
    }
    public Double getProfit() {
        return this.profit;
    }
    
    public void setProfit(Double profit) {
        this.profit = profit;
    }
    public Date getSellDate() {
        return this.sellDate;
    }
    
    public void setSellDate(Date sellDate) {
        this.sellDate = sellDate;
    }




}


