package model;
// Generated Oct 30, 2016 9:18:27 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ShopUser generated by hbm2java
 */
public class ShopUser  implements java.io.Serializable {


     private Integer userId;
     private String email;
     private String password;
     private Date regDate;
     private String contactNo;
     private Integer roleId;
     private String address;
     private String country;
     private String district;
     private String zipCode;
     private String shoperName;

    public ShopUser() {
    }

    public ShopUser(String email, String password, Date regDate, String contactNo, Integer roleId, String address, String country, String district, String zipCode, String shoperName) {
       this.email = email;
       this.password = password;
       this.regDate = regDate;
       this.contactNo = contactNo;
       this.roleId = roleId;
       this.address = address;
       this.country = country;
       this.district = district;
       this.zipCode = zipCode;
       this.shoperName = shoperName;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getRegDate() {
        return this.regDate;
    }
    
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }
    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }
    public Integer getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }
    public String getZipCode() {
        return this.zipCode;
    }
    
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }
    public String getShoperName() {
        return this.shoperName;
    }
    
    public void setShoperName(String shoperName) {
        this.shoperName = shoperName;
    }




}


