package model;
// Generated Oct 30, 2016 9:18:27 AM by Hibernate Tools 4.3.1



/**
 * Sliderfont generated by hbm2java
 */
public class Sliderfont  implements java.io.Serializable {


     private Integer id;
     private String title;
     private String desc;
     private String imgUrl;

    public Sliderfont() {
    }

    public Sliderfont(String title, String desc, String imgUrl) {
       this.title = title;
       this.desc = desc;
       this.imgUrl = imgUrl;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDesc() {
        return this.desc;
    }
    
    public void setDesc(String desc) {
        this.desc = desc;
    }
    public String getImgUrl() {
        return this.imgUrl;
    }
    
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }




}


