package model;
// Generated Oct 30, 2016 9:18:27 AM by Hibernate Tools 4.3.1



/**
 * SubCategory generated by hbm2java
 */
public class SubCategory  implements java.io.Serializable {


     private Integer subCatId;
     private Integer catId;
     private String subCatName;
     private String subCatDesc;

    public SubCategory() {
    }

    public SubCategory(Integer catId, String subCatName, String subCatDesc) {
       this.catId = catId;
       this.subCatName = subCatName;
       this.subCatDesc = subCatDesc;
    }
   
    public Integer getSubCatId() {
        return this.subCatId;
    }
    
    public void setSubCatId(Integer subCatId) {
        this.subCatId = subCatId;
    }
    public Integer getCatId() {
        return this.catId;
    }
    
    public void setCatId(Integer catId) {
        this.catId = catId;
    }
    public String getSubCatName() {
        return this.subCatName;
    }
    
    public void setSubCatName(String subCatName) {
        this.subCatName = subCatName;
    }
    public String getSubCatDesc() {
        return this.subCatDesc;
    }
    
    public void setSubCatDesc(String subCatDesc) {
        this.subCatDesc = subCatDesc;
    }




}


