package model;
// Generated Oct 30, 2016 9:18:27 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * UserTrans generated by hbm2java
 */
public class UserTrans  implements java.io.Serializable {


     private Integer id;
     private String userEmail;
     private Integer proId;
     private String proName;
     private Double price;
     private Integer qty;
     private Double total;
     private Date trDate;
     private String tx;

    public UserTrans() {
    }

	
    public UserTrans(Date trDate) {
        this.trDate = trDate;
    }
    public UserTrans(String userEmail, Integer proId, String proName, Double price, Integer qty, Double total, Date trDate, String tx) {
       this.userEmail = userEmail;
       this.proId = proId;
       this.proName = proName;
       this.price = price;
       this.qty = qty;
       this.total = total;
       this.trDate = trDate;
       this.tx = tx;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }
    public Integer getProId() {
        return this.proId;
    }
    
    public void setProId(Integer proId) {
        this.proId = proId;
    }
    public String getProName() {
        return this.proName;
    }
    
    public void setProName(String proName) {
        this.proName = proName;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Date getTrDate() {
        return this.trDate;
    }
    
    public void setTrDate(Date trDate) {
        this.trDate = trDate;
    }
    public String getTx() {
        return this.tx;
    }
    
    public void setTx(String tx) {
        this.tx = tx;
    }




}


