package model;
// Generated Oct 30, 2016 9:18:27 AM by Hibernate Tools 4.3.1



/**
 * Userinfo generated by hbm2java
 */
public class Userinfo  implements java.io.Serializable {


     private int user;
     private String pass;

    public Userinfo() {
    }

	
    public Userinfo(int user) {
        this.user = user;
    }
    public Userinfo(int user, String pass) {
       this.user = user;
       this.pass = pass;
    }
   
    public int getUser() {
        return this.user;
    }
    
    public void setUser(int user) {
        this.user = user;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }




}


